### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by asifparvez199** [Kenokey/Tiktok-Zefoy-Generator#5]
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome-stable: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome-beta: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome-dev: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome-stable: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome-beta: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome-dev: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome-stable: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome-beta: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome-dev: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome-stable: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome-beta: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome-dev: not found/data/data/com.termux/files/usr/bin/sh: 1: google-chrome: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome-stable: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome-beta: not found
/data/data/com.termux/files/usr/bin/sh: 1: google-chrome-dev: not foundTraceback (most recent call last):
  File "/data/data/com.termux/files/home/Tiktok-Zefoy-Generator/main.py", line 320, in <module>
    main = Main()
           ^^^^^^
  File "/data/data/com.termux/files/home/Tiktok-Zefoy-Generator/main.py", line 26, in __init__
    self.driver = Chrome(executable_path=ChromeDriverManager().install(), options=self.options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/undetected_chromedriver/__init__.py", line 378, in __init__
    raise FileNotFoundError(
FileNotFoundError:
---------------------
Could not determine browser executable.
---------------------
Make sure your browser is installed in the default location (path).
If you are sure about the browser executable, you can specify it using
the `browser_executable_path='/path/to/browser/executable` parameter.

**Comment by Kenokey** [comment]
You need to install Google Chrome
